apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv-master-apps-webservices-webinf"
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  nfs:
    path: "/var/nfs/unison-openshift/webservices-webinf"
    server: "nfs-dev.tremolo.lan"
  persistentVolumeReclaimPolicy: "Recycle"
