apiVersion: v1
kind: Pod
metadata:
  name: unison-slave
  labels:
    name: unison-slave
spec:
  containers:
    - resources:
      image: tremolosecurity/unison:latest
      name: unison
      env:
        - name: JAVA_OPTS
          value:
      ports:
        - containerPort: 8080
          protocol: TCP
          name: proxy-open
        - containerPort: 8443
          protocol: TCP
          name: proxy-secure
        - containerPort: 9090
          protocol: TCP
          name: admin-secure
        - containerPort: 9093
          protocol: TCP
          name: ws-secure
      volumeMounts:
        - name: unison-proxy-auth
          mountPath: /usr/local/tremolo/tremolo-service/apps/proxy/auth
        - name: unison-proxy-webinf
          mountPath: /usr/local/tremolo/tremolo-service/apps/proxy/WEB-INF
        - name: unison-tremoloadmin-webinf
          mountPath: /usr/local/tremolo/tremolo-service/apps/tremolo-admin/WEB-INF
        - name: unison-webservices-webinf
          mountPath: /usr/local/tremolo/tremolo-service/apps/webservices/WEB-INF
        - name: unison-conf
          mountPath: /usr/local/tremolo/tremolo-service/conf
        - name: unison-extlib
          mountPath: /usr/local/tremolo/tremolo-service/ext-lib
  volumes:
    - name: unison-proxy-auth
      persistentVolumeClaim:
        claimName: pvc-slave-apps-proxy-auth
        readOnly: true
    - name: unison-proxy-webinf
      persistentVolumeClaim:
        claimName: pvc-slave-apps-proxy-webinf
        readOnly: true
    - name: unison-tremoloadmin-webinf
      persistentVolumeClaim:
        claimName: pvc-slave-apps-tremoloadmin-webinf
        readOnly: true
    - name: unison-webservices-webinf
      persistentVolumeClaim:
        claimName: pvc-slave-apps-webservices-webinf
        readOnly: true
    - name: unison-conf
      persistentVolumeClaim:
        claimName: pvc-slave-conf
        readOnly: true
    - name: unison-extlib
      persistentVolumeClaim:
        claimName: pvc-slave-extlib
        readOnly: true
