apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv-slave-conf"
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadOnlyMany"
  nfs:
    path: "/var/nfs/unison-openshift/conf"
    server: "nfs-dev.tremolo.lan"
  persistentVolumeReclaimPolicy: "Recycle"
