apiVersion: v1
kind: Service
metadata:
  name: unison-slave
spec:
  selector:
    name: unison-slave
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    name: secure
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: open
